baseurl = "https://zhiyi-r.github.io/"
title = "南风知我意~"
theme = "hugo-coder"
languagecode = "zh"
defaultcontentlanguage = "zh"


[pagination]
pagerSize = 20

[services]
# [services.disqus]
# shortname = "ZhiYi"

[markup.highlight]
style = "github-dark"

[params]
author = "ZhiYi"
info = "Empty Stack DevOps"
description = "知意的小站"
keywords = "blog,developer,personal"
# avatarurl = "images/avatar.jpg"
# gravatar = "john.doe@example.com"
faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2024

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/ZhiYi-R/"

# Menu links
[[menu.main]]
name = "文章"
weight = 1
url = "posts/"
[[menu.main]]
name = "关于"
weight = 2
url = "authors/"
