baseURL = 'https://zhiyi-r.github.io/'
languageCode = 'zh'
defaultContentLanguage = "zh"
title = '南风知我意~'
theme='hugo-coder'
enableEmoji = true

[params]
author = '知意'
description = '知意的个人博客'
keywords = 'blog,developer,personal,electronic,programming'
info = ['Empty Stack DevOps']
colorScheme = 'dark'
hideColorSchemeToggle = false
since = 2024


[params.utteranc]
enable = true
repo = 'ZhiYi-R/ZhiYi.github.io'
issueTerm = 'title'
theme = 'github-dark'

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/ZhiYi-R/"

[languages.zh]
languageName = ":zh:"

[[languages.zh.menu.main]]
name = "文章"
weight = 1
url = "post/"

[[languages.zh.menu.main]]
name = "关于"
weight = 2
url = "authors/"

